### ISSUE TITLE
GitHub removed an API used - api.py requires an updated logic

### ISSUE THREAD

**Issue by consideRatio** [minrk/ghpro#19]
### Bug description

https://github.com/minrk/ghpro/blob/c39b03f1300d0fe18e7cd1a8bf1566973708b37c/ghpro/api.py#L94-L95

I note that support for using this endpoint was removed nov 13 2020 as described in [this documentation about the API](https://docs.github.com/en/enterprise-server@3.0/rest/reference/oauth-authorizations#create-a-new-authorization). In [this blog post](https://developer.github.com/changes/2020-02-14-deprecating-oauth-auth-endpoint/) they suggest a new strategy, `web-application-flow` which is described [here](https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#web-application-flow).

### How to reproduce

I tried using `backport-pr` and got the following...

```
jupyterhub git:(1.4.x) backport-pr apply 1.4.x 3531
Backport PR #3531 onto 1.4.x
/home/erik/miniforge3/lib/python3.7/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/home/erik/miniforge3/lib/python3.7/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Please enter your github login and password.  Password is not stored, only used to get an oAuth token. You can revoke this at any time on Github. At the following URL:https://github.com/settings/tokens
Username: asdf
Password: 
Traceback (most recent call last):
  File "/home/erik/miniforge3/bin/backport-pr", line 10, in <module>
    sys.exit(main())
  File "/home/erik/dev/contrib/minrk/ghpro/ghpro/backport.py", line 238, in main
    if backport_pr(path, branch, pr, project):
  File "/home/erik/dev/contrib/minrk/ghpro/ghpro/backport.py", line 84, in backport_pr
    pr = get_pull_request(project, num, auth=True)
  File "/home/erik/dev/contrib/minrk/ghpro/ghpro/api.py", line 148, in get_pull_request
    header = make_auth_header()
  File "/home/erik/dev/contrib/minrk/ghpro/ghpro/api.py", line 118, in make_auth_header
    return {'Authorization': 'token ' + get_auth_token()}
  File "/home/erik/dev/contrib/minrk/ghpro/ghpro/api.py", line 57, in get_auth_token
    _, token = get_username_and_auth_token(project=project, store=store)
  File "/home/erik/dev/contrib/minrk/ghpro/ghpro/api.py", line 111, in get_username_and_auth_token
    response.raise_for_status()
  File "/home/erik/miniforge3/lib/python3.7/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/authorizations
```

**Comment by minrk** [comment]
Probably makes sense to remove this feature and require users to get and provide the token via env (like GitHub-activity)
