### ISSUE TITLE
Keyring not working since OSX upgrade ?

### ISSUE THREAD

**Issue by Carreau** [minrk/ghpro#4]
Do you experience something similar to the following:

```
Traceback (most recent call last):
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/keyring/backends/OS_X.py", line 35, in set_password
    api.set_generic_password(self.keychain, service, username, password)
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/keyring/backends/_OS_X_API.py", line 157, in set_generic_password
    NotFound.raise_for_status(status, "Unable to set password")
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/keyring/backends/_OS_X_API.py", line 43, in raise_for_status
    Error.raise_for_status(status, msg)
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/keyring/backends/_OS_X_API.py", line 35, in raise_for_status
    raise cls(status, msg)
keyring.backends._OS_X_API.Error: (-25293, 'Unable to set password')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bussonniermatthias/anaconda/bin/github-stats", line 10, in <module>
    sys.exit(main())
  File "/Users/bussonniermatthias/dev/ghpro/ghpro/stats.py", line 158, in main
    auth=True)
  File "/Users/bussonniermatthias/dev/ghpro/ghpro/api.py", line 187, in get_milestone_id
    milestones = get_milestones(project, auth=auth, **params)
  File "/Users/bussonniermatthias/dev/ghpro/ghpro/api.py", line 180, in get_milestones
    headers = make_auth_header()
  File "/Users/bussonniermatthias/dev/ghpro/ghpro/api.py", line 85, in make_auth_header
    return {'Authorization': 'token ' + get_auth_token()}
  File "/Users/bussonniermatthias/dev/ghpro/ghpro/api.py", line 81, in get_auth_token
    keyring.set_password('github', fake_username, token)
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/keyring/core.py", line 48, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/keyring/backends/OS_X.py", line 37, in set_password
    raise PasswordSetError("Can't store password on keychain")
keyring.errors.PasswordSetError: Can't store password on keychain
```

Which seem to be a keyring issue: https://github.com/jaraco/keyring/issues/219 but should be solved ?

**Comment by minrk** [comment]
I haven't seen it, but I don't think I've entered a new token since the upgrade.

**Comment by Carreau** [comment]
Well, it's entering is failing, but getting is regularly failing as well... it's a bit annoying. 
But anyways. I'll close soonish if it seem to be only a problem with my system.

**Comment by Carreau** [comment]
hum.. working now....
